services:
  db:
    image: postgres:13
    container_name: user-api
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: userapi
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
